name: ProductHub CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarQube Begin
        run: |
          dotnet sonarscanner begin \
            /k:"bhavsar-kevin_ProductHub" \
            /o:"bhavsar-kevin" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
        
      - name: Generate coverage report
        run: reportgenerator 
          -reports:**/coverage.cobertura.xml 
          -targetdir:coverage-report 
          -reporttypes:Html
          
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: "**/coverage.cobertura.xml"

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: coveragereport

      - name: SonarQube End
        run: |
          dotnet sonarscanner end \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"